options:
  formatter: stylish
files:
  include:
    - "src/**/*.scss"
  ignore:
    - "node_modules/**/*.s+(a|c)ss"
rules:
  no-duplicate-properties: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0