version: '2'

services:
  site:
    image: eponae/charts
    command:
    - -prometheusMetricsHost
    - charts:1080
    - -csp
    - "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' maps.googleapis.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: csi.gstatic.com maps.gstatic.com maps.googleapis.com; connect-src 'self' api.eponae.fr"
    - -env
    - GOOGLE_MAPS_KEY
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: charts.eponae.fr'
      traefik.port: '1080'
    environment:
      GOOGLE_MAPS_KEY: '${GOOGLE_MAPS_KEY}'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
