version: '2'

services:
  site:
    image: eponae/charts
    command:
    - -csp
    - default-src 'self' *.googleapis.com *.gstatic.com; script-src 'self' 'unsafe-inline' maps.googleapis.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com; connect-src api.eponae.fr
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: charts.eponae.fr'
      traefik.port: '1080'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
